version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
volumes:
  postgres: